"""empty message

Revision ID: 81ed6ef0366f
Revises: 6ba94d086e24
Create Date: 2024-05-23 17:27:08.004067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ed6ef0366f'
down_revision: Union[str, None] = '6ba94d086e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('currency', sa.String(), nullable=True))
    op.drop_column('operation', 'figi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('figi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('operation', 'currency')
    # ### end Alembic commands ###
